import type { AppData, Deck } from './types';

/** [front, back] pairs — 102 common words & everyday sentences per deck. */
type Pair = [string, string];

const EN_PL: Pair[] = [
  ['hello', 'cześć'],
  ['good morning', 'dzień dobry'],
  ['good night', 'dobranoc'],
  ['goodbye', 'do widzenia'],
  ['please', 'proszę'],
  ['thank you', 'dziękuję'],
  ['sorry', 'przepraszam'],
  ['yes', 'tak'],
  ['no', 'nie'],
  ['maybe', 'może'],
  ['today', 'dzisiaj'],
  ['tomorrow', 'jutro'],
  ['yesterday', 'wczoraj'],
  ['now', 'teraz'],
  ['later', 'później'],
  ['here', 'tutaj'],
  ['there', 'tam'],
  ['water', 'woda'],
  ['bread', 'chleb'],
  ['milk', 'mleko'],
  ['coffee', 'kawa'],
  ['tea', 'herbata'],
  ['beer', 'piwo'],
  ['apple', 'jabłko'],
  ['meat', 'mięso'],
  ['cheese', 'ser'],
  ['egg', 'jajko'],
  ['soup', 'zupa'],
  ['dinner', 'obiad'],
  ['breakfast', 'śniadanie'],
  ['house', 'dom'],
  ['door', 'drzwi'],
  ['window', 'okno'],
  ['kitchen', 'kuchnia'],
  ['room', 'pokój'],
  ['bed', 'łóżko'],
  ['table', 'stół'],
  ['chair', 'krzesło'],
  ['key', 'klucz'],
  ['car', 'samochód'],
  ['bus', 'autobus'],
  ['train', 'pociąg'],
  ['airplane', 'samolot'],
  ['bicycle', 'rower'],
  ['street', 'ulica'],
  ['city', 'miasto'],
  ['shop', 'sklep'],
  ['money', 'pieniądze'],
  ['work', 'praca'],
  ['school', 'szkoła'],
  ['book', 'książka'],
  ['pen', 'długopis'],
  ['phone', 'telefon'],
  ['computer', 'komputer'],
  ['dog', 'pies'],
  ['cat', 'kot'],
  ['bird', 'ptak'],
  ['horse', 'koń'],
  ['fish', 'ryba'],
  ['tree', 'drzewo'],
  ['flower', 'kwiat'],
  ['sun', 'słońce'],
  ['moon', 'księżyc'],
  ['rain', 'deszcz'],
  ['snow', 'śnieg'],
  ['weather', 'pogoda'],
  ['family', 'rodzina'],
  ['mother', 'mama'],
  ['father', 'tata'],
  ['brother', 'brat'],
  ['sister', 'siostra'],
  ['child', 'dziecko'],
  ['friend', 'przyjaciel'],
  ['man', 'mężczyzna'],
  ['woman', 'kobieta'],
  ['day', 'dzień'],
  ['night', 'noc'],
  ['week', 'tydzień'],
  ['month', 'miesiąc'],
  ['year', 'rok'],
  ['time', 'czas'],
  ['big', 'duży'],
  ['small', 'mały'],
  ['good', 'dobry'],
  ['bad', 'zły'],
  ['new', 'nowy'],
  ['old', 'stary'],
  ['hot', 'gorący'],
  ['cold', 'zimny'],
  ['happy', 'szczęśliwy'],
  ['How are you?', 'Jak się masz?'],
  ['What is your name?', 'Jak masz na imię?'],
  ['My name is Anna.', 'Mam na imię Anna.'],
  ["I don't understand.", 'Nie rozumiem.'],
  ['Can you help me?', 'Czy możesz mi pomóc?'],
  ['Where is the bathroom?', 'Gdzie jest łazienka?'],
  ['How much does it cost?', 'Ile to kosztuje?'],
  ['I would like a coffee, please.', 'Poproszę kawę.'],
  ['What time is it?', 'Która jest godzina?'],
  ["I'm learning Polish.", 'Uczę się polskiego.'],
  ['See you tomorrow!', 'Do zobaczenia jutro!'],
  ['Have a nice day!', 'Miłego dnia!'],
];

const ES_EN: Pair[] = [
  ['hola', 'hello'],
  ['buenos días', 'good morning'],
  ['buenas noches', 'good night'],
  ['adiós', 'goodbye'],
  ['por favor', 'please'],
  ['gracias', 'thank you'],
  ['lo siento', 'sorry'],
  ['sí', 'yes'],
  ['no', 'no'],
  ['quizás', 'maybe'],
  ['hoy', 'today'],
  ['mañana', 'tomorrow'],
  ['ayer', 'yesterday'],
  ['ahora', 'now'],
  ['después', 'later'],
  ['aquí', 'here'],
  ['allí', 'there'],
  ['el agua', 'the water'],
  ['el pan', 'the bread'],
  ['la leche', 'the milk'],
  ['el café', 'the coffee'],
  ['el té', 'the tea'],
  ['la cerveza', 'the beer'],
  ['la manzana', 'the apple'],
  ['la carne', 'the meat'],
  ['el queso', 'the cheese'],
  ['el huevo', 'the egg'],
  ['la sopa', 'the soup'],
  ['la cena', 'the dinner'],
  ['el desayuno', 'the breakfast'],
  ['la casa', 'the house'],
  ['la puerta', 'the door'],
  ['la ventana', 'the window'],
  ['la cocina', 'the kitchen'],
  ['la habitación', 'the room'],
  ['la cama', 'the bed'],
  ['la mesa', 'the table'],
  ['la silla', 'the chair'],
  ['la llave', 'the key'],
  ['el coche', 'the car'],
  ['el autobús', 'the bus'],
  ['el tren', 'the train'],
  ['el avión', 'the airplane'],
  ['la bicicleta', 'the bicycle'],
  ['la calle', 'the street'],
  ['la ciudad', 'the city'],
  ['la tienda', 'the shop'],
  ['el dinero', 'the money'],
  ['el trabajo', 'the job'],
  ['la escuela', 'the school'],
  ['el libro', 'the book'],
  ['el bolígrafo', 'the pen'],
  ['el teléfono', 'the phone'],
  ['el ordenador', 'the computer'],
  ['el perro', 'the dog'],
  ['el gato', 'the cat'],
  ['el pájaro', 'the bird'],
  ['el caballo', 'the horse'],
  ['el pescado', 'the fish'],
  ['el árbol', 'the tree'],
  ['la flor', 'the flower'],
  ['el sol', 'the sun'],
  ['la luna', 'the moon'],
  ['la lluvia', 'the rain'],
  ['la nieve', 'the snow'],
  ['el tiempo', 'the weather'],
  ['la familia', 'the family'],
  ['la madre', 'the mother'],
  ['el padre', 'the father'],
  ['el hermano', 'the brother'],
  ['la hermana', 'the sister'],
  ['el niño', 'the child'],
  ['el amigo', 'the friend'],
  ['el hombre', 'the man'],
  ['la mujer', 'the woman'],
  ['el día', 'the day'],
  ['la noche', 'the night'],
  ['la semana', 'the week'],
  ['el mes', 'the month'],
  ['el año', 'the year'],
  ['grande', 'big'],
  ['pequeño', 'small'],
  ['bueno', 'good'],
  ['malo', 'bad'],
  ['nuevo', 'new'],
  ['viejo', 'old'],
  ['caliente', 'hot'],
  ['frío', 'cold'],
  ['feliz', 'happy'],
  ['triste', 'sad'],
  ['¿Cómo estás?', 'How are you?'],
  ['¿Cómo te llamas?', 'What is your name?'],
  ['Me llamo Ana.', 'My name is Ana.'],
  ['No entiendo.', "I don't understand."],
  ['¿Puedes ayudarme?', 'Can you help me?'],
  ['¿Dónde está el baño?', 'Where is the bathroom?'],
  ['¿Cuánto cuesta esto?', 'How much does this cost?'],
  ['Me gustaría un café, por favor.', "I'd like a coffee, please."],
  ['¿Qué hora es?', 'What time is it?'],
  ['Estoy aprendiendo español.', "I'm learning Spanish."],
  ['Nos vemos mañana en la estación.', 'See you tomorrow at the station.'],
  ['¡Que tengas un buen día!', 'Have a nice day!'],
];

function buildDeck(name: string, pairs: Pair[]): Deck {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    name,
    createdAt: now,
    cards: pairs.map(([front, back]) => ({
      id: crypto.randomUUID(),
      front,
      back,
      level: 0,
      lastReviewed: null,
      createdAt: now,
    })),
  };
}

/** First-run demo content (deck names are user data — not translated). */
export function seedData(): AppData {
  return {
    version: 1,
    decks: [buildDeck('English → Polish', EN_PL), buildDeck('Spanish → English', ES_EN)],
  };
}
